server:
  port: 8088

spring:
  datasource:
        url: jdbc:mysql://mysql-197f1a7d-datbkpro225280-40b0.g.aivencloud.com:24899/defaultdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: AVNS_kaRXyO8GQVV6iyNjDvF
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    open-in-view: false

api:
  prefix: api/v1

jwt:
  expiration: 2592000
  secret-key: 2WJ11AX24EkdyGLBt0031TjHoU5/FA47qWohEx26DCI=
